# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Github Actions CI

on: pull_request

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: view the PR number
      run: |
        echo "PR number = ${{ github.event.pull_request.number }}"
        echo "PR number = ${{ env.PR_NUMBER }}"
